name: gh-pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly

      - run: pwsh test.ps1
